namespace MenuPlanner.Enums
{
    public enum FoodGroup
    {
        Vegetables,         // agurk, paprika, salat, sopp, ...
        Fruits,             // epler, pærer, bananer, druer, ...
        Dairy,              // melk, fløte, rømme, yoghurt, ...
        DairySubstitutes,   // margarin, soyamelk, soyayoghurt, ...
        Grains,             // korn, mel, quinoa, brun ris, ...
        Meats,              // storfe, svin, lam, elg, ...
        MeatSubstitutes,    // tofu, 
        Poultry,            // kylling, kalkun, and, rype, ...
        Eggs,               // hønseegg, vaktelegg, måsegg, ...
        Seafood,            // reker, hummer, blekksprut, blåskjell, ...
        Legumes,            // (belgvekster) linser, bønner, kikerter, ...
        NutsAndSeeds,       // mandler, valnøtter, solsikkekjerner, chiafrø, ...
        HerbsAndSpices,     // pepper, spisskummen, dill, karri, ...
        Sweeteners,         // sukker, melis, stevia, honning, ...
        Condiments,         // salt, sennep, majones, soyasaus, ...
        Other
    }
}
