namespace MenuPlanner.Enums
{
    public enum FoodGroup
    {
        Vegetables,         // agurk, paprika, salat, sopp, ...
        Fruits,             // epler, pærer, bananer, druer, hel kokosnøtt, ...
        Dairy,              // melk, fløte, rømme, yoghurt, ost, ...
        DairySubstitutes,   // margarin, soyamelk, mandelmelk, soyayoghurt, ...
        Grains,             // korn, mel, gryn, quinoa, brun ris, ...
        Meats,              // storfe, svin, lam, elg, rein, rådyr, ...
        MeatSubstitutes,    // tofu, 
        Poultry,            // kylling, kalkun, and, rype, ...
        Eggs,               // hønseegg, vaktelegg, måsegg, ...
        Seafood,            // reker, hummer, blekksprut, blåskjell, ...
        Legumes,            // (belgvekster) linser, bønner, kikerter, ...
        NutsAndSeeds,       // mandler, valnøtter, solsikkekjerner, chiafrø, ...
        HerbsAndSpices,     // pepper, spisskummen, dill, karri, sitrongress, ...
        Sweeteners,         // sukker, melis, stevia, honning, ...
        Condiments,         // salt, sennep, majones, soyasaus, curry paste, ...
        Oils,               // rapsolje, maisolje, olivenolje, sesamolje, ...
        CoconutProducts,    // kokosmasse, kokosmelk, kokoskrem, kokosvann ...
        Other
    }
}
